using UltimateWardrobe.Patcher;
using UltimateWardrobe.Tests.Scanner;

namespace UltimateWardrobe.Tests.Patcher;

/// <summary>
/// Sprint 5.3.3 - <see cref="OutputFolder"/> unit tests (plan section 4.6): the sanitized mod/plugin
/// name, the resolved mod-dir path staying strictly under the output directory, the typed
/// <see cref="Core.Abstractions.PatchException"/> for a file-as-output-dir and for locked content,
/// delete-then-rebuild clearing stale files, and the <c>meta.ini</c> layout with a
/// <c>generated</c> stamp differing between runs.
/// </summary>
public sealed class OutputFolderTests
{
    [Fact]
    public void ModName_AddsPrefix_AndSanitizesIllegalFileNameChars()
    {
        var name = OutputFolder.ModName("Iron:Set*With?Bad<>Chars");

        Assert.Equal("UltimateWardrobe - Iron_Set_With_Bad__Chars", name);
        foreach (var invalid in Path.GetInvalidFileNameChars())
        {
            Assert.DoesNotContain(invalid, name);
        }
    }

    [Fact]
    public void ModName_TrimsTrailingDotsAndSpaces()
    {
        Assert.Equal("UltimateWardrobe - Armor", OutputFolder.ModName("Armor. "));
        Assert.Equal("UltimateWardrobe - Armor", OutputFolder.ModName("Armor..."));
    }

    [Theory]
    [InlineData("")]
    [InlineData("   ")]
    public void ModName_BlankName_Throws(string name)
    {
        Assert.Throws<ArgumentException>(() => OutputFolder.ModName(name));
    }

    [Fact]
    public void ModName_AllIllegalName_FallsBackToUnnamed()
    {
        Assert.Equal("UltimateWardrobe - Unnamed", OutputFolder.ModName("..."));
    }

    [Fact]
    public void ModName_AlwaysStartsWithThePrefix()
    {
        Assert.StartsWith("UltimateWardrobe - ", OutputFolder.ModName("a/b: c?"));
    }

    [Fact]
    public void PluginFileName_EqualsModNamePlusEsp()
    {
        Assert.Equal(OutputFolder.ModName("E2eTest") + ".esp", OutputFolder.PluginFileName("E2eTest"));
    }

    [Fact]
    public void ResolveModDir_ResolvesStrictlyUnderTheOutputDir()
    {
        using var dir = new TestTempDir();
        var outputDir = Path.Combine(dir.Root, "Export");

        var modDir = OutputFolder.ResolveModDir(outputDir, "E2eTest");

        Assert.Equal(Path.GetFullPath(outputDir), Path.GetDirectoryName(modDir));
        Assert.Equal(Path.Combine(outputDir, "UltimateWardrobe - E2eTest"), modDir);
    }

    [Fact]
    public void ResolveModDir_OutputDirIsAFile_ThrowsPatchException()
    {
        using var dir = new TestTempDir();
        var asFile = Path.Combine(dir.Root, "a-file");
        File.WriteAllText(asFile, "content");

        var ex = Assert.Throws<PatchException>(
            () => OutputFolder.ResolveModDir(asFile, "E2eTest"));

        Assert.Contains("refusing to clear", ex.Message, StringComparison.Ordinal);
    }

    [Fact]
    public void ClearModDir_DeletesStaleContent_AndRecreatesEmpty()
    {
        using var dir = new TestTempDir();
        var modDir = Path.Combine(dir.Root, "UltimateWardrobe - Stale");
        Directory.CreateDirectory(modDir);
        File.WriteAllText(Path.Combine(modDir, "stale.bsa"), "stale");
        Directory.CreateDirectory(Path.Combine(modDir, "meshes", "orphan"));
        File.WriteAllText(Path.Combine(modDir, "meshes", "orphan", "ghost.nif"), "stale");

        OutputFolder.ClearModDir(modDir);

        Assert.True(Directory.Exists(modDir));
        Assert.Empty(Directory.EnumerateFileSystemEntries(modDir));
    }

    [Fact]
    public void ClearModDir_LockedContent_ThrowsPatchException()
    {
        using var dir = new TestTempDir();
        var modDir = Path.Combine(dir.Root, "UltimateWardrobe - Locked");
        Directory.CreateDirectory(modDir);

        using (new FileStream(Path.Combine(modDir, "held.bin"), FileMode.Create, FileAccess.ReadWrite, FileShare.None))
        {
            var ex = Assert.Throws<PatchException>(
                () => OutputFolder.ClearModDir(modDir));

            Assert.Contains("clear", ex.Message, StringComparison.OrdinalIgnoreCase);
        }
    }

    [Fact]
    public void WriteMetaIni_WritesTheSection4Point6Layout()
    {
        using var dir = new TestTempDir();
        var modDir = Path.Combine(dir.Root, "UltimateWardrobe - Iron Test");
        Directory.CreateDirectory(modDir);

        var path = OutputFolder.WriteMetaIni(modDir, "Iron Test", 3, new DateTime(2026, 8, 28, 12, 34, 0, DateTimeKind.Utc));

        Assert.Equal(Path.Combine(modDir, "meta.ini"), path);
        Assert.Equal(
            "[General]\n" +
            "name=UltimateWardrobe - Iron Test\n" +
            "version=1.0.0\n" +
            "category=Armor Replacer\n" +
            "notes=Generated by UltimateWardrobe on 2026-08-28 12:34:00 UTC. Overhaul: Iron Test, 3 sets mapped.\n" +
            "generated=2026-08-28 12:34:00 UTC\n",
            File.ReadAllText(path));
    }

    [Fact]
    public void WriteMetaIni_GeneratedLine_DiffersBetweenRuns()
    {
        using var dir = new TestTempDir();
        var modDir = Path.Combine(dir.Root, "UltimateWardrobe - Repeated");
        Directory.CreateDirectory(modDir);

        var first = OutputFolder.WriteMetaIni(modDir, "Repeated", 1, new DateTime(2026, 1, 1, 10, 0, 0, DateTimeKind.Utc));
        var firstContent = File.ReadAllText(first);
        var second = OutputFolder.WriteMetaIni(modDir, "Repeated", 1, new DateTime(2026, 1, 1, 10, 0, 1, DateTimeKind.Utc));

        Assert.NotEqual(firstContent, File.ReadAllText(second));
        Assert.Equal("generated=2026-01-01 10:00:01 UTC",
            File.ReadAllLines(second).Single(l => l.StartsWith("generated=", StringComparison.Ordinal)));
    }
}
