using Mutagen.Bethesda.Plugins;
using Mutagen.Bethesda.Plugins.Records;
using Mutagen.Bethesda.Skyrim;
using UltimateWardrobe.Core.Abstractions;
using UltimateWardrobe.Core.Domain;
using UltimateWardrobe.Core.Enums;
using UltimateWardrobe.Patcher;
using UltimateWardrobe.Tests.Scanner;

namespace UltimateWardrobe.Tests.Patcher;

/// <summary>
/// Sprint 5.3.3 - the <see cref="WardrobePatcher"/> end-to-end pipeline over the synthetic mini
/// universe (two mappings on two target sets: the cuirass with donor physics/body-slide and the
/// helmet with body + physics patch overlays). Asserts: the plugin + report + meta.ini + the exact
/// whitelisted output tree (no extra files), the reopened esp records (override WorldModel paths,
/// ESL flag, <c>UW_</c> EditorID prefix, auto-collected masters), two-run determinism (identical esp
/// bytes and report), re-export cleanliness (stale/orphaned files and stale meta.ini fields gone),
/// coarse <see cref="PatchProgress"/>, and the typed <see cref="PatchException"/>s for a locked
/// export folder and a missing catalog.
/// </summary>
public sealed class WardrobePatcherTests
{
    private const string OverhaulName = "E2eTest";
    private const string ModName = "UltimateWardrobe - E2eTest";

    // ---------------------------------------------------------------------------------------------
    // End-to-end happy path
    // ---------------------------------------------------------------------------------------------

    [Fact]
    public async Task Build_EndToEnd_CreatesModFolder_PluginMetaAndReport()
    {
        using var dir = new TestTempDir();
        var (overhaul, library) = CreateE2eWorld(dir);
        var outputDir = Path.Combine(dir.Root, "Output");
        var exportDir = Path.Combine(outputDir, ModName);
        var reports = new List<PatchProgress>();

        var result = await new WardrobePatcher().BuildAsync(overhaul, library, outputDir, new Progress<PatchProgress>(reports.Add));

        // Layout: the esp + meta.ini + the exact whitelisted sliced files, nothing else.
        var pluginPath = Path.Combine(exportDir, ModName + ".esp");
        Assert.Equal(pluginPath, result.PluginPath);
        Assert.True(File.Exists(pluginPath));
        Assert.Equal(ExpectedSlicedFiles, result.CopiedFiles);
        Assert.Equal(ExpectedOutputTree, OutputTree(exportDir));

        // Report numbers.
        var report = result.Report!;
        Assert.Equal(2, report.TotalMappings);
        Assert.Equal(2, report.ResolvedMappings);
        Assert.Equal(0, report.SkippedMappings);
        Assert.Equal(2, report.OverriddenRecords);
        Assert.Equal(ExpectedSlicedFiles, report.CopiedFiles);
        Assert.True(report.CopiedBytes > 0);
        Assert.Empty(report.Warnings);

        // The reopened esp: ESL gate on, overridden ARMA WorldModel slots, UW_ prefix, masters.
        using var reopened = SkyrimMod.CreateFromBinaryOverlay(pluginPath, SkyrimRelease.SkyrimSE);
        Assert.True(reopened.IsSmallMaster);
        Assert.Contains(SyntheticSkyrimMods.MiniUniverseKey, reopened.MasterReferences.Select(m => m.Master));

        var cuirass = reopened.ArmorAddons[SyntheticSkyrimMods.MiniIronCuirassAddonKey];
        Assert.Equal("UW_IronCuirassAA", cuirass.EditorID);
        Assert.Equal("meshes/donor/iron/m/cuirass.nif", cuirass.WorldModel!.Male!.File!.GivenPath);
        Assert.Equal("meshes/armor/mini/IronCuirass/female.nif", cuirass.WorldModel.Female!.File!.GivenPath);

        var helmet = reopened.ArmorAddons[SyntheticSkyrimMods.MiniIronHelmetAddonKey];
        Assert.Equal("UW_IronHelmetAA", helmet.EditorID);
        Assert.Equal("meshes/donor/iron/h/helmet.nif", helmet.WorldModel!.Male!.File!.GivenPath);
        Assert.Equal("meshes/armor/mini/IronHelmet/female.nif", helmet.WorldModel.Female!.File!.GivenPath);

        // meta.ini: section 4.6 layout with the mapped-set count and a non-empty generated stamp.
        var meta = File.ReadAllText(Path.Combine(exportDir, "meta.ini"));
        Assert.Contains("[General]", meta, StringComparison.Ordinal);
        Assert.Contains("name=UltimateWardrobe - E2eTest", meta, StringComparison.Ordinal);
        Assert.Contains("version=1.0.0", meta, StringComparison.Ordinal);
        Assert.Contains("category=Armor Replacer", meta, StringComparison.Ordinal);
        Assert.Contains("notes=Generated by UltimateWardrobe on ", meta, StringComparison.Ordinal);
        Assert.Contains("Overhaul: E2eTest, 2 sets mapped.", meta, StringComparison.Ordinal);
        var generated = File.ReadAllLines(Path.Combine(exportDir, "meta.ini")).Single(l => l.StartsWith("generated=", StringComparison.Ordinal));
        Assert.Matches(@"generated=\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2} UTC", generated);

        // Progress: one coarse update per pipeline stage.
        Assert.Equal(5, reports.Count);
        Assert.Equal(new[] { "Resolve targets", "Prepare export folder", "Build esp plugin", "Copy donor files", "Write meta.ini" },
            reports.Select(p => p.Stage).ToArray());
        Assert.Equal(5, reports[^1].Completed);
        Assert.Equal(5, reports[^1].Total);
    }

    // ---------------------------------------------------------------------------------------------
    // Determinism + re-export cleanliness
    // ---------------------------------------------------------------------------------------------

    [Fact]
    public async Task Build_TwoRuns_ProduceIdenticalEspBytesAndReport()
    {
        using var dir = new TestTempDir();
        var (overhaul, library) = CreateE2eWorld(dir);
        var outputDir = Path.Combine(dir.Root, "Determinism");
        var patcher = new WardrobePatcher();

        var first = await patcher.BuildAsync(overhaul, library, outputDir);
        var firstEspBytes = File.ReadAllBytes(first.PluginPath);

        var second = await patcher.BuildAsync(overhaul, library, outputDir);

        Assert.Equal(firstEspBytes, File.ReadAllBytes(second.PluginPath));
        Assert.Equal(first.Report!.TotalMappings, second.Report!.TotalMappings);
        Assert.Equal(first.Report.ResolvedMappings, second.Report.ResolvedMappings);
        Assert.Equal(first.Report.SkippedMappings, second.Report.SkippedMappings);
        Assert.Equal(first.Report.OverriddenRecords, second.Report.OverriddenRecords);
        Assert.Equal(first.Report.CopiedFiles, second.Report.CopiedFiles);
        Assert.Equal(first.Report.CopiedBytes, second.Report.CopiedBytes);
        Assert.Equal(first.Report.Warnings.Count, second.Report.Warnings.Count);
    }

    [Fact]
    public async Task Build_ReExport_ClearsStaleFilesAndStaleMetaFields()
    {
        using var dir = new TestTempDir();
        var (overhaul, library) = CreateE2eWorld(dir);
        var outputDir = Path.Combine(dir.Root, "ReExport");
        var patcher = new WardrobePatcher();

        var firstEspBytes = File.ReadAllBytes((await patcher.BuildAsync(overhaul, library, outputDir)).PluginPath);

        // Plant stale/orphaned content from a previous export.
        var exportDir = Path.Combine(outputDir, ModName);
        var orphanMesh = Path.Combine(exportDir, "meshes", "orphan", "ghost.nif");
        Directory.CreateDirectory(Path.GetDirectoryName(orphanMesh)!);
        File.WriteAllText(orphanMesh, "stale-mesh");
        File.WriteAllText(Path.Combine(exportDir, "orphan.bsa"), "stale-archive");
        File.WriteAllText(Path.Combine(exportDir, "stray.txt"), "stale-stray");
        File.WriteAllText(Path.Combine(exportDir, "meta.ini"),
            "[General]\nname=Stale\nstalekey=yes\ngenerated=1970-01-01 00:00 'UTC'\n");

        await patcher.BuildAsync(overhaul, library, outputDir);

        // The output tree is exactly the whitelisted set again - stale files are gone - and the
        // esp is byte-identical to the first export.
        Assert.Equal(ExpectedOutputTree, OutputTree(exportDir));
        Assert.Equal(firstEspBytes, File.ReadAllBytes(Path.Combine(exportDir, ModName + ".esp")));

        var meta = File.ReadAllText(Path.Combine(exportDir, "meta.ini"));
        Assert.DoesNotContain("stalekey", meta, StringComparison.Ordinal);
        Assert.Matches(@"generated=\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2} UTC",
            File.ReadAllLines(Path.Combine(exportDir, "meta.ini")).Single(l => l.StartsWith("generated=", StringComparison.Ordinal)));
    }

    // ---------------------------------------------------------------------------------------------
    // Typed build-blocking failures
    // ---------------------------------------------------------------------------------------------

    [Fact]
    public async Task Build_LockedExportFolder_ThrowsPatchException()
    {
        using var dir = new TestTempDir();
        var (overhaul, library) = CreateE2eWorld(dir);
        var outputDir = Path.Combine(dir.Root, "Locked");
        var patcher = new WardrobePatcher();

        // A previous export left a file held with FileShare.None: the clean-before-write step fails.
        var modDir = Path.Combine(outputDir, ModName);
        Directory.CreateDirectory(modDir);
        using (new FileStream(Path.Combine(modDir, "held.bin"), FileMode.Create, FileAccess.ReadWrite, FileShare.None))
        {
            var ex = await Assert.ThrowsAsync<PatchException>(() => patcher.BuildAsync(overhaul, library, outputDir));

            Assert.Contains("clear", ex.Message, StringComparison.OrdinalIgnoreCase);
        }
    }

    [Fact]
    public async Task Build_MissingCatalog_ThrowsPatchException_BeforeAnyOutputIsTouched()
    {
        using var dir = new TestTempDir();
        SyntheticSkyrimMods.WriteMiniUniverse(dir.Root);
        var donor = WriteDonor(dir.Root, "donor-e2e", new[] { "meshes/donor/iron/m/cuirass.nif" });

        var projectId = Guid.NewGuid();
        var overhaul = new Overhaul(Guid.NewGuid(), "NoCatalog", projectId,
            new VanillaCatalogSource(dir.Root, new[] { SyntheticSkyrimMods.MiniUniverseFileName }));
        var library = MakeLibrary(donor.Asset);
        var outputDir = Path.Combine(dir.Root, "NoCatalogExport");

        await Assert.ThrowsAsync<PatchException>(() =>
            new WardrobePatcher().BuildAsync(overhaul, library, outputDir));

        Assert.False(Directory.Exists(Path.Combine(outputDir, "UltimateWardrobe - NoCatalog")));
    }

    // ---------------------------------------------------------------------------------------------
    // Fixtures
    // ---------------------------------------------------------------------------------------------

    /// <summary>The exact whitelisted sliced files (game-relative, ordinal) for the two mappings.</summary>
    private static readonly IReadOnlyList<string> ExpectedSlicedFiles = new[]
    {
        "CalienteTools/BodySlide/SliderSets/BodyConvert.osp",
        "CalienteTools/BodySlide/SliderSets/IronCuirassBodySlide.osp",
        "CalienteTools/BodySlide/SliderSets/IronHelmetBodySlide.osp",
        "SKSE/Plugins/BodyXml.xml",
        "SKSE/Plugins/IronCuirassPhysics.xml",
        "SKSE/Plugins/Physics.xml",
        "meshes/donor/iron/h/helmet.nif",
        "meshes/donor/iron/h/helmet_1st.nif",
        "meshes/donor/iron/m/cuirass.nif",
        "meshes/donor/iron/m/cuirass_1st.nif",
        "meshes/donor/iron/m/cuirass_1stperson.nif",
        "textures/donor/iron/h/helmet.dds",
        "textures/donor/iron/m/cuirass.dds",
    };

    /// <summary>The full mod folder tree: sliced files + the esp + meta.ini (ordinal).</summary>
    private static readonly IReadOnlyList<string> ExpectedOutputTree = new[]
    {
        "CalienteTools/BodySlide/SliderSets/BodyConvert.osp",
        "CalienteTools/BodySlide/SliderSets/IronCuirassBodySlide.osp",
        "CalienteTools/BodySlide/SliderSets/IronHelmetBodySlide.osp",
        "SKSE/Plugins/BodyXml.xml",
        "SKSE/Plugins/IronCuirassPhysics.xml",
        "SKSE/Plugins/Physics.xml",
        "UltimateWardrobe - E2eTest.esp",
        "meshes/donor/iron/h/helmet.nif",
        "meshes/donor/iron/h/helmet_1st.nif",
        "meshes/donor/iron/m/cuirass.nif",
        "meshes/donor/iron/m/cuirass_1st.nif",
        "meshes/donor/iron/m/cuirass_1stperson.nif",
        "meta.ini",
        "textures/donor/iron/h/helmet.dds",
        "textures/donor/iron/m/cuirass.dds",
    };

    private static (Overhaul Overhaul, UltimateWardrobe.Core.Domain.DonorLibrary Library) CreateE2eWorld(TestTempDir dir)
    {
        SyntheticSkyrimMods.WriteMiniUniverse(dir.Root);

        var donor = WriteDonor(dir.Root, "donor-e2e",
            new[]
            {
                "meshes/donor/iron/m/cuirass.nif",
                "meshes/donor/iron/m/cuirass_1st.nif",
                "meshes/donor/iron/m/cuirass_1stperson.nif",
                "meshes/donor/iron/m/cuirass_0.nif",
                "meshes/donor/iron/h/helmet.nif",
                "meshes/donor/iron/h/helmet_1st.nif",
                "textures/donor/iron/m/cuirass.dds",
                "textures/donor/iron/h/helmet.dds",
                "textures/donor/iron/h/junk.txt",
                "CalienteTools/BodySlide/SliderSets/IronCuirassBodySlide.osp",
                "CalienteTools/BodySlide/SliderSets/IronHelmetBodySlide.osp",
                "SKSE/Plugins/IronCuirassPhysics.xml",
                "SKSE/Plugins/IronHelmetPhysics.xml",
            },
            bodySlide: new[]
            {
                "CalienteTools/BodySlide/SliderSets/IronCuirassBodySlide.osp",
                "CalienteTools/BodySlide/SliderSets/IronHelmetBodySlide.osp",
            },
            physics: new[]
            {
                "SKSE/Plugins/IronCuirassPhysics.xml",
                "SKSE/Plugins/IronHelmetPhysics.xml",
            });

        var body = WriteDonor(dir.Root, "body-patch",
            new[]
            {
                "meshes/donor/iron/h/helmet.nif",
                "CalienteTools/BodySlide/SliderSets/BodyConvert.osp",
                "SKSE/Plugins/BodyXml.xml",
                "Docs/readme.txt",
            },
            kind: DonorAssetKind.BodyConversionPatch);

        var physics = WriteDonor(dir.Root, "physics-patch",
            new[]
            {
                "meshes/donor/iron/h/helmet.nif",
                "SKSE/Plugins/Physics.xml",
                "readme.txt",
            },
            kind: DonorAssetKind.PhysicsPatch);

        var catalog = CreateCatalog(dir.Root);
        var project = new Project(Guid.NewGuid(), "WardrobePatcherProject", "C:/Projects/Test");
        var overhaul = new Overhaul(Guid.NewGuid(), OverhaulName, project.Id, catalog.Source) { Catalog = catalog };

        overhaul.Mappings.Add(new PieceMapping(
            Guid.NewGuid(), overhaul.Id, "IronArmor", "IronCuirass", Gender.Male,
            donor.Asset.ImportId, "DonorIronCuirass", "meshes/donor/iron/m/cuirass.nif"));

        overhaul.Mappings.Add(new PieceMapping(
            Guid.NewGuid(), overhaul.Id, "HelmetSet", "IronHelmet", Gender.Male,
            donor.Asset.ImportId, "DonorIronHelmet", "meshes/donor/iron/h/helmet.nif",
            bodyConversionPatchAssetId: body.Asset.ImportId,
            physicsPatchAssetId: physics.Asset.ImportId));

        return (overhaul, MakeLibrary(donor.Asset, body.Asset, physics.Asset));
    }

    private static Catalog CreateCatalog(string root)
    {
        var cuirass = new Variant(Gender.Male, WeightClass.Heavy, new[]
        {
            new Piece("IronCuirass", SyntheticSkyrimMods.MiniIronCuirassKey.ID, "32 Body", "IronCuirassAA", SyntheticSkyrimMods.MiniIronCuirassMalePath),
        });
        var helmet = new Variant(Gender.Male, WeightClass.Heavy, new[]
        {
            new Piece("IronHelmet", SyntheticSkyrimMods.MiniIronHelmetKey.ID, "32 Body", "IronHelmetAA", "meshes/armor/mini/IronHelmet/male.nif"),
        });

        return new Catalog(
            new VanillaCatalogSource(root, new[] { SyntheticSkyrimMods.MiniUniverseFileName }),
            new[] { new ArmorSet("IronArmor", "Iron", new[] { cuirass }), new ArmorSet("HelmetSet", "Helmet", new[] { helmet }) });
    }

    private static (string Directory, DonorAsset Asset) WriteDonor(
        string parent,
        string name,
        IReadOnlyList<string> files,
        IReadOnlyList<string>? bodySlide = null,
        IReadOnlyList<string>? physics = null,
        DonorAssetKind kind = DonorAssetKind.FullReplacer)
    {
        var directory = Path.Combine(parent, name);
        Directory.CreateDirectory(directory);

        var manifest = new List<DonorFileEntry>(files.Count);
        foreach (var file in files)
        {
            WriteAndCreate(file, directory);
            manifest.Add(new DonorFileEntry(file, new FileInfo(Path.Combine(directory, file.Replace('/', Path.DirectorySeparatorChar))).Length));
        }

        var asset = new DonorAsset(
            Guid.NewGuid(),
            name + ".7z",
            directory,
            DateTime.UtcNow,
            "hash-" + name,
            kind,
            fileManifest: manifest,
            detectedBodySlideFiles: bodySlide ?? Array.Empty<string>(),
            detectedPhysicsFiles: physics ?? Array.Empty<string>());

        return (directory, asset);
    }

    private static void WriteAndCreate(string relativePath, string root)
    {
        var full = Path.Combine(root, relativePath.Replace('/', Path.DirectorySeparatorChar));
        var parent = Path.GetDirectoryName(full);
        if (!string.IsNullOrEmpty(parent))
        {
            Directory.CreateDirectory(parent);
        }

        File.WriteAllText(full, Path.GetFileName(root) + "::" + relativePath);
    }

    private static UltimateWardrobe.Core.Domain.DonorLibrary MakeLibrary(params DonorAsset[] assets)
    {
        var library = new UltimateWardrobe.Core.Domain.DonorLibrary(Guid.NewGuid());
        library.Assets.AddRange(assets);
        return library;
    }

    private static IReadOnlyList<string> OutputTree(string root)
    {
        return Directory.EnumerateFiles(root, "*", SearchOption.AllDirectories)
            .Select(f => Path.GetRelativePath(root, f).Replace('\\', '/'))
            .OrderBy(p => p, StringComparer.Ordinal)
            .ToArray();
    }
}
