<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\UltimateWardrobe.Core\UltimateWardrobe.Core.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="..\..\runtimes\win-x64\native\7z.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <Link>runtimes\win-x64\native\7z.dll</Link>
    </Content>
    <Content Include="..\..\runtimes\win-x64\native\UnRAR64.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <Link>runtimes\win-x64\native\UnRAR64.dll</Link>
    </Content>
  </ItemGroup>

</Project>
